/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TestWithdrawalFailTesterInterface extends Interface {
  getFunction(
    nameOrSignature: "executeCreateSeason" | "executeWithdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeCreateSeason",
    values: [AddressLike, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithdraw",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeCreateSeason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithdraw",
    data: BytesLike
  ): Result;
}

export interface TestWithdrawalFailTester extends BaseContract {
  connect(runner?: ContractRunner | null): TestWithdrawalFailTester;
  waitForDeployment(): Promise<this>;

  interface: TestWithdrawalFailTesterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeCreateSeason: TypedContractMethod<
    [
      target: AddressLike,
      name: string,
      price: BigNumberish,
      cap: BigNumberish,
      dur: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeWithdraw: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeCreateSeason"
  ): TypedContractMethod<
    [
      target: AddressLike,
      name: string,
      price: BigNumberish,
      cap: BigNumberish,
      dur: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithdraw"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  filters: {};
}
