/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BiodiversityCredits_LatinHack } from "./BiodiversityCredits_LatinHack";
export type { BiodiversityCredits_LatinHack_LatinHack } from "./BiodiversityCredits_LatinHack_LatinHack";
