/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BiodiversityCredits_LatinHack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BiodiversityCredits_LatinHack__factory>;
    getContractFactory(
      name: "CarbonCredits_LatinHack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CarbonCredits_LatinHack__factory>;
    getContractFactory(
      name: "CSA_LatinHack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CSA_LatinHack__factory>;
    getContractFactory(
      name: "ICarbonCredits_LatinHack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICarbonCredits_LatinHack__factory>;
    getContractFactory(
      name: "TestCSALatinHackHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestCSALatinHackHelper__factory>;
    getContractFactory(
      name: "TestWithdrawalFailTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestWithdrawalFailTester__factory>;
    getContractFactory(
      name: "RecyclingCredits_LatinHack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RecyclingCredits_LatinHack__factory>;

    getContractAt(
      name: "BiodiversityCredits_LatinHack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BiodiversityCredits_LatinHack>;
    getContractAt(
      name: "CarbonCredits_LatinHack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CarbonCredits_LatinHack>;
    getContractAt(
      name: "CSA_LatinHack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CSA_LatinHack>;
    getContractAt(
      name: "ICarbonCredits_LatinHack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICarbonCredits_LatinHack>;
    getContractAt(
      name: "TestCSALatinHackHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestCSALatinHackHelper>;
    getContractAt(
      name: "TestWithdrawalFailTester",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestWithdrawalFailTester>;
    getContractAt(
      name: "RecyclingCredits_LatinHack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RecyclingCredits_LatinHack>;

    deployContract(
      name: "BiodiversityCredits_LatinHack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BiodiversityCredits_LatinHack>;
    deployContract(
      name: "CarbonCredits_LatinHack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CarbonCredits_LatinHack>;
    deployContract(
      name: "CSA_LatinHack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CSA_LatinHack>;
    deployContract(
      name: "ICarbonCredits_LatinHack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICarbonCredits_LatinHack>;
    deployContract(
      name: "TestCSALatinHackHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestCSALatinHackHelper>;
    deployContract(
      name: "TestWithdrawalFailTester",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestWithdrawalFailTester>;
    deployContract(
      name: "RecyclingCredits_LatinHack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RecyclingCredits_LatinHack>;

    deployContract(
      name: "BiodiversityCredits_LatinHack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BiodiversityCredits_LatinHack>;
    deployContract(
      name: "CarbonCredits_LatinHack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CarbonCredits_LatinHack>;
    deployContract(
      name: "CSA_LatinHack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CSA_LatinHack>;
    deployContract(
      name: "ICarbonCredits_LatinHack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICarbonCredits_LatinHack>;
    deployContract(
      name: "TestCSALatinHackHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestCSALatinHackHelper>;
    deployContract(
      name: "TestWithdrawalFailTester",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestWithdrawalFailTester>;
    deployContract(
      name: "RecyclingCredits_LatinHack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RecyclingCredits_LatinHack>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
