/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BiodiversityCredits_LatinHack__factory } from "./BiodiversityCredits_LatinHack__factory";
export { BiodiversityCredits_LatinHack_LatinHack__factory } from "./BiodiversityCredits_LatinHack_LatinHack__factory";
